repos:

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: python
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python, pyi]

-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: [
          '--ignore=F405,F403,E226,,E226,W504,W503,E121,E126,E211,E225,E501,E203,E402,F401,F811,E231'
        ]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=1024']
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-xml
    - id: check-json
    - id: check-yaml

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: python -m pytest -vv tests
        types: [python]
        always_run: true
